### ISSUE TITLE
Network not working for Jeyapriya

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/Admin#1]
Dear Senthil,

Network not working for Jeyapriya.

**Comment by senthil19** [comment]
Completed it is working fine

**Comment by astpl1998** [comment]
DueDate:24-06-2019
Remarks:excellent

**Comment by astpl1998** [comment]
DueDate:26-06-2019
Remarks:excellent

**Comment by astpl1998** [comment]
DueDate:30-06-2019
Remarks:GOOD

**Comment by astpl1998** [comment]
DueDate:27-08-19
Remarks:good
