### ISSUE TITLE
KNK-Laptop mainboard not well & Internal Keyboard not working

### ISSUE THREAD

**Issue by knovakaspar** [astpl1998/Admin#14]
Dear Senthil,

As you Advised Laptop mainboard issue resolved and I have used the External Keyboard.Now Working Perfect.
Pl, find the below Service Detail.
![Service Bill](https://user-images.githubusercontent.com/50448138/102179154-aeb0b980-3ecc-11eb-8de1-c36740ecb40c.jpeg)

Thank u for your guidance.

Thanks & Regards
NovaKaspar

**Comment by senthil19** [comment]
Closed
