### ISSUE TITLE
Inner Board IC get crashed

### ISSUE THREAD

**Issue by knovakaspar** [astpl1998/Admin#23]
Dear Senthil,

As Discussed, last week my laptop had an IC problem then had a complete service now working perfectly.
Please find the below attached service details.
![IMG_20210610_100807](https://user-images.githubusercontent.com/50448138/121466184-9c738c00-c9d4-11eb-8b39-cf876a69080d.JPG)

Thank you for your guidance.

Regards
Nova

**Comment by raju-kurup** [comment]
Issue resolved so closing this ticket
